site_name: DevOps Learning and Research
use_directory_urls: false
theme:
  name: material

markdown_extensions:
  - toc:
      permalink: true

plugins:
  # plugin used to add search capability to site
  - search
  - glightbox

  # allow clickable sections that lead to an index page - https://oprypin.github.io/mkdocs-section-index/
  - section-index
  - literate-nav

nav:
  - Home: index.md
  - About: about.md
  - Certifications:
    - certifications/certifications.md
    - Certified Kubernetes Administrator (CKA):
      - certifications/CKA.md
      - certifications/CKA/*
    - Certified Kubernetes Security Specialist (CKS):
      - certifications/CKS.md
      - certifications/CKS/*
    - Green Software for Practitioners:
      - certifications/green-software-for-practitioners.md
      - certifications/green-software-for-practitioners/*
    - HashiCorp Certified - Terraform Associate:
      - certifications/terraform-associate.md
      - certifications/terraform-associate/01_Deploying-Infrastructure.md
      - certifications/terraform-associate/02_Working-With-Configurations.md
      - certifications/terraform-associate/03_Provisioners.md
      - certifications/terraform-associate/04_Modules-and-Workspaces.md
      - certifications/terraform-associate/05_Remote-State-Management.md
      - certifications/terraform-associate/06_Security.md
      - certifications/terraform-associate/07_Terraform-Cloud-and-Enterprise.md
      - certifications/terraform-associate/08_Exam-Preparation.md
    - HashiCorp Certified - Vault Associate:
      - certifications/vault-associate.md
      - certifications/vault-associate/*