site_name: DevOps Learning and Research
use_directory_urls: false
theme:
  name: material

plugins:
  # plugin used to add search capability to site
  - search
  - glightbox

  # allow clickable sections that lead to an index page - https://oprypin.github.io/mkdocs-section-index/
  - section-index
  - literate-nav

nav:
  - Home: index.md
  - About: about.md
  - Certifications:
    - certifications/certifications.md
    - Certified Kubernetes Administrator (CKA):
      - certifications/CKA.md
      - certifications/CKA/01_Course-Introduction.md
      - certifications/CKA/02_Core-Concepts.md
      - certifications/CKA/03_Scheduling.md
      - certifications/CKA/04_Logging-and-Monitoring.md
      - certifications/CKA/05_Application-Lifecycle-Management.md
      - certifications/CKA/06_Cluster-Maintenance.md
      - certifications/CKA/07_Security.md
      - certifications/CKA/08_Storage.md
      - certifications/CKA/09_Networking.md
      - certifications/CKA/10_Design-a-Kubernetes-Cluster.md
      - certifications/CKA/11_Install-Kubernetes-the-kubeadm-way.md
      - certifications/CKA/13_Troubleshooting.md
      - certifications/CKA/14_JSONpath-introduction.md
    - Certified Kubernetes Security Specialist (CKS):
      - certifications/CKS.md
      - certifications/CKS/01_Introduction.md
      - certifications/CKS/02_The-Kubernetes-Attack-Surface.md
      - certifications/CKS/03_Cluster-Setup-and-Hardening.md
      - certifications/CKS/04_System-Hardening.md
      - certifications/CKS/05_Minimize-Microservice-Vulnerabilities.md
      - certifications/CKS/06_Supply-Chain-Security.md
      - certifications/CKS/07_Monitoring-Logging-and-Runtime-Security.md
    - HashiCorp Certified - Terraform Associate:
      - certifications/terraform-associate.md
      - certifications/terraform-associate/01_Deploying-Infrastructure.md
      - certifications/terraform-associate/02_Working-With-Configurations.md
      - certifications/terraform-associate/03_Provisioners.md
      - certifications/terraform-associate/04_Modules-and-Workspaces.md
      - certifications/terraform-associate/05_Remote-State-Management.md
      - certifications/terraform-associate/06_Security.md
      - certifications/terraform-associate/07_Terraform-Cloud-and-Enterprise.md
      - certifications/terraform-associate/08_Exam-Preparation.md