name: certifications-notes markdownlint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  markdown-ci:

    defaults:
      run:
        shell: bash

    runs-on: ubuntu-latest

    steps:
    - name: Chekout the Repo
      uses: actions/checkout@v4

    - uses: articulate/actions-markdownlint@v1
      name: markdown-lint - Ansible
      with:
        config: .markdownlint.json
        files: 'ansible/**/*.md'

    - uses: articulate/actions-markdownlint@v1
      name: markdown-lint - AWS
      if: (success() || failure())
      with:
        config: .markdownlint.json
        files: 'aws/**/**/*.mdc'

    - uses: articulate/actions-markdownlint@v1
      name: markdown-lint - Packer
      if: (success() || failure())
      with:
        config: .markdownlint.json
        files: 'hashicorp/packer/**/*.md'

    - uses: articulate/actions-markdownlint@v1
      name: markdown-lint - Terraform
      if: (success() || failure())
      with:
        config: .markdownlint.json
        files: 'hashicorp/terraform/**/*.md'

    - uses: articulate/actions-markdownlint@v1
      name: markdown-lint - Vault
      if: (success() || failure())
      with:
        config: .markdownlint.json
        files: 'hashicorp/vault/**/*.md'

    - uses: articulate/actions-markdownlint@v1
      name: markdown-lint - Kubernetes and GitOps
      if: (success() || failure())
      with:
        config: .markdownlint.json
        files: 'kubernetes/**/**/*.md'

    - uses: articulate/actions-markdownlint@v1
      name: markdown-lint - VMware
      if: (success() || failure())
      with:
        config: .markdownlint.json
        files: 'vmware/**/**/*.md'

    - uses: articulate/actions-markdownlint@v1
      name: markdown-lint - Green Software Practitioner
      if: (success() || failure())
      with:
        config: .markdownlint.json
        files: 'green-software-for-practitioners/**/**/*.md'

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install pymdown-extensions
      - run: pip install mkdocs-glightbox
      - run: pip install mkdocs-section-index
      - run: pip install mkdocs-literate-nav
      - run: mkdocs gh-deploy --force

  deploy_mkdocs:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
