name: devops-learnings markdownlint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  markdown-ci:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest

    steps:
    - name: Chekout the Repo
      uses: actions/checkout@v5

    - uses: articulate/actions-markdownlint@v1
      name: markdown-lint - Certifications
      with:
        config: .markdownlint.json
        files: 'docs/certifications/*.md'

    - uses: articulate/actions-markdownlint@v1
      name: markdown-lint - Tooling
      with:
        config: .markdownlint.json
        files: 'docs/tooling/*.md'

  deploy-mkdocs:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    needs: markdown-ci

    steps:
    - name: Chekout the Repo
      uses: actions/checkout@v5
    - name: Configure Git Credentials
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
    - uses: actions/setup-python@v5
      name: Setup Python
      with:
        python-version: 3.x
    - run: pip install mkdocs-material
    - run: pip install pymdown-extensions
    - run: pip install mkdocs-glightbox
    - run: pip install mkdocs-section-index
    - run: pip install mkdocs-literate-nav
    - run: pip install mkdocs-exclude
    - run: mkdocs gh-deploy --force