name: certifications-notes CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  markdown-ci:

    defaults:
      run:
        shell: bash

    runs-on: ubuntu-latest

    steps:
    - name: Chekout the Repo
      uses: actions/checkout@v3

    - uses: articulate/actions-markdownlint@v1
      name: markdown-lint - Packer
      with:
        config: .markdownlint.json
        files: 'hashicorp/packer/**/*.md'
        version: 0.37.0