name: certifications-notes CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  markdown-ci:

    defaults:
      run:
        shell: bash

    runs-on: ubuntu-latest

    steps:
    - name: Chekout the Repo
      uses: actions/checkout@v3

    - uses: articulate/actions-markdownlint@v1
      name: markdown-lint - Ansible
      with:
        config: .markdownlint.json
        files: 'ansible/**/*.md'

    - uses: articulate/actions-markdownlint@v1
      name: markdown-lint - AWS
      if: (success() || failure())
      with:
        config: .markdownlint.json
        files: 'aws/**/*.md'

    - uses: articulate/actions-markdownlint@v1
      name: markdown-lint - Packer
      if: (success() || failure())
      with:
        config: .markdownlint.json
        files: 'hashicorp/packer/**/*.md'

    - uses: articulate/actions-markdownlint@v1
      name: markdown-lint - Terraform
      if: (success() || failure())
      with:
        config: .markdownlint.json
        files: 'hashicorp/terraform/**/*.md'

    - uses: articulate/actions-markdownlint@v1
      name: markdown-lint - Vault
      if: (success() || failure())
      with:
        config: .markdownlint.json
        files: 'hashicorp/vault/**/*.md'

    - uses: articulate/actions-markdownlint@v1
      name: markdown-lint - Kubernetes and GitOps
      if: (success() || failure())
      with:
        config: .markdownlint.json
        files: 'kubernetes/**/*.md'

    - uses: articulate/actions-markdownlint@v1
      name: markdown-lint - VMware
      if: (success() || failure())
      with:
        config: .markdownlint.json
        files: 'vmware/**/*.md'